site_name: Cloud-V Docs
nav:
- Home:
    - Cloud-V: index.md
- For Software Developers:
    - RISC-V CI User's Guide:
        - Guide for Software Developer: Software_Developer_Guide.md
        - Creating a Jenkinfile: Creating_jenkinsfile.md
- For Administrators:
    - Jenkins Docs:
        - Building Jenkins: Building_Jenkins_github_repo.md
        - Creating Jenkins Node on LXC: Creating_Jenkins_Node_on_LXC.md
        - Creating a pipeline project: Creating_CI_CD_pipeline.md
        - Creating Multinode pipelines: Multinode_Pipelines.md
        - Adding custom-build packages in Jenkins: Adding_Custom-build_packages_in_Jenkins.md
        - Github Push webhook integration: jenkins_github_integration/Github_push_webhook.md
        - Github PR webhook integration: jenkins_github_integration/Github_PR_webhook_integration.md
        - GitLab Integration: jenkins_gitlab_integration.md
        - Letsencrypt configuration with Jenkins: Installing_ssl_certificates_new.md
    - QEMU and Linux Kernel:
        - Installing Qemu for RISC-V: Building_qemu.md
        - Building Linux kernel and booting on QEMU: Building_Linux_Kernel.md
        - Booting RISC-V Ubuntu 22.04 on qemu-system-riscv64: Booting_ubuntu22.04_riscv64
    - Cross-Compilation:
        - Overview: Cross_Compiling/Overview.md
        - Cross Compiling Python3.8.15: Cross_Compiling/Cross_compiling python3.8.15.md
        - Cross Compiling Openssl: Cross_Compiling/Cross_compiling_openssl.md
        - Cross Compiling Ruby: Cross_Compiling/Cross_compiling_ruby.md
        - Cross Compiling Drhystone: Cross_Compiling/Cross_compiling_dhrystone.md
        - Cross Compiling Coremark: Cross_Compiling/Cross_compiling_coremark
        - Cross Compiling Rust: Cross_Compiling/Cross_compiling_rust.md
        - Cross Compiling go: Cross_Compiling/Cross_compiling_go.md

    - Usage monitoring:
        - Setting up Grafana and Prometheus: Usage_Monitoring/Prometheus_Grafana.md
        - Integrating Prometheus with Grafana: Usage_Monitoring/Integrating_prometheus_grafana.md
theme: readthedocs
